version: '3.3'
services:
  db:
    image: mysql:5
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - ./data/magento_db:/docker-entrypoint-initdb.d
  app:
    build: .
    volumes:
      - .:/test_drupal
    depends_on:
      - db
